# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/2021autum/computerarchitectureseminar/computer_architecture/lab3/CPU_CDE/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2021autum/computerarchitectureseminar/computer_architecture/lab3/CPU_CDE/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/2021autum/computerarchitectureseminar/computer_architecture/lab3/CPU_CDE/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2021autum/computerarchitectureseminar/computer_architecture/lab3/CPU_CDE/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
